### ISSUE TITLE
En tant que visiteur je veux ajouter un produit au panier

### ISSUE THREAD

**Issue by DmDespert** [DmDespert/dbeat#7]
Créer les liens nécessaires avec la BDD et la session utilisateur pour le bon fonctionnement du panier.

- [x] Créer le bouton ajouter au panier
- [x] Implémenter la session
- [x] faire le formulaire
- [x] validation du formulaire
- [x] Lier le produit ajouté, au panier
- [x] Afficher le produit dans le panier
- [x] Afficher tous les produits du panier et leur quantité respective

**Comment by cbouvat** [comment]
Merci de découpé en plusieurs user storie, on découpe en "en tant que visiteur, je peux ajouter au panier" "en tant que visiteur, je peux modifier la quantité dans le panier", ...
